package ru.ekrupin.ivi.core.ui

object IviTestTags {
    const val APP_ROOT = "ivi_app_root"

    const val NAV_HOME = "nav_home"
    const val NAV_EVENTS = "nav_events"
    const val NAV_WEIGHT = "nav_weight"
    const val NAV_EVENT_TYPES = "nav_event_types"
    const val NAV_SETTINGS = "nav_settings"

    const val HOME_ROOT = "home_root"
    const val HOME_PET_OVERVIEW = "home_pet_overview"
    const val HOME_PET_PHOTO = "home_pet_photo"
    const val HOME_EDIT_PET_BUTTON = "home_edit_pet_button"
    const val HOME_ADD_EVENT_BUTTON = "home_add_event_button"
    const val HOME_OPEN_WEIGHT_BUTTON = "home_open_weight_button"
    const val HOME_OPEN_SETTINGS_BUTTON = "home_open_settings_button"
    const val HOME_CONFLICT_CARD = "home_conflict_card"
    const val HOME_OPEN_CONFLICTS_BUTTON = "home_open_conflicts_button"
    const val HOME_NO_ACTIVE_EVENTS = "home_no_active_events"

    const val SETTINGS_ROOT = "settings_root"
    const val SETTINGS_SYNC_SECTION = "settings_sync_section"
    const val SETTINGS_SYNC_BASE_URL_FIELD = "settings_sync_base_url_field"
    const val SETTINGS_SYNC_EMAIL_FIELD = "settings_sync_email_field"
    const val SETTINGS_SYNC_DISPLAY_NAME_FIELD = "settings_sync_display_name_field"
    const val SETTINGS_SYNC_PASSWORD_FIELD = "settings_sync_password_field"
    const val SETTINGS_CONNECTION_STATUS = "settings_connection_status"
    const val SETTINGS_SYNC_STATUS = "settings_sync_status"
    const val SETTINGS_LOGIN_BUTTON = "settings_login_button"
    const val SETTINGS_REGISTER_BUTTON = "settings_register_button"
    const val SETTINGS_LOGOUT_BUTTON = "settings_logout_button"
    const val SETTINGS_MANUAL_SYNC_BUTTON = "settings_manual_sync_button"
    const val SETTINGS_NO_SERVER_PET_CARD = "settings_no_server_pet_card"
    const val SETTINGS_PUBLISH_LOCAL_BUTTON = "settings_publish_local_button"
    const val SETTINGS_REPLACE_FROM_SERVER_BUTTON = "settings_replace_from_server_button"
    const val SETTINGS_CONFLICT_CARD = "settings_conflict_card"
    const val SETTINGS_OPEN_CONFLICTS_BUTTON = "settings_open_conflicts_button"

    const val INVITE_SECTION = "invite_section"
    const val PET_ACCESS_STATUS = "pet_access_status"
    const val CREATE_INVITE_BUTTON = "create_invite_button"
    const val INVITE_CODE_TEXT = "invite_code_text"
    const val INVITE_COPY_BUTTON = "invite_copy_button"
    const val ACCEPT_INVITE_CODE_FIELD = "accept_invite_code_field"
    const val ACCEPT_INVITE_BUTTON = "accept_invite_button"
    const val LEAVE_PET_BUTTON = "leave_pet_button"
    const val TRANSFER_OWNER_BUTTON_PREFIX = "transfer_owner_button_"
    const val DELETE_PET_CONFIRM_BUTTON = "delete_pet_confirm_button"

    const val PET_EDIT_ROOT = "pet_edit_root"
    const val PET_EDIT_PHOTO_AREA = "pet_edit_photo_area"
    const val PET_EDIT_CHANGE_PHOTO_BUTTON = "pet_edit_change_photo_button"
    const val PET_EDIT_REMOVE_PHOTO_BUTTON = "pet_edit_remove_photo_button"
    const val PET_EDIT_NAME_FIELD = "pet_edit_name_field"
    const val PET_EDIT_SAVE_BUTTON = "pet_edit_save_button"

    const val EVENT_TYPES_ROOT = "event_types_root"
    const val EVENT_TYPE_ADD_BUTTON = "event_type_add_button"
    const val EVENT_TYPE_NAME_FIELD = "event_type_name_field"
    const val EVENT_TYPE_SAVE_BUTTON = "event_type_save_button"

    const val EVENTS_ROOT = "events_root"
    const val EVENT_CREATE_BUTTON = "event_create_button"
    const val EVENT_EDIT_BUTTON_PREFIX = "event_edit_button_"
    const val EVENT_EDIT_ROOT = "event_edit_root"
    const val EVENT_COMMENT_FIELD = "event_comment_field"
    const val EVENT_SAVE_BUTTON = "event_save_button"
    const val EVENT_DELETE_BUTTON = "event_delete_button"

    const val WEIGHT_ROOT = "weight_root"
    const val WEIGHT_ADD_BUTTON = "weight_add_button"
    const val WEIGHT_VALUE_FIELD = "weight_value_field"
    const val WEIGHT_COMMENT_FIELD = "weight_comment_field"
    const val WEIGHT_SAVE_BUTTON = "weight_save_button"

    const val CONFLICTS_ROOT = "conflicts_root"
    const val CONFLICT_LIST = "conflict_list"
    const val CONFLICT_ITEM_PREFIX = "conflict_item_"
    const val CONFLICT_ACCEPT_SERVER_BUTTON_PREFIX = "conflict_accept_server_button_"
    const val CONFLICT_RETRY_LOCAL_BUTTON_PREFIX = "conflict_retry_local_button_"
}
